const mockItems = [
    {
        "id": "itm_001",
        "type": "lost",
        "title": "Black Redmi Phone",
        "category": "Phone",
        "image": "https://picsum.photos/seed/phone/600/400",
        "location": "Library - Level 2",
        "date": "2 days ago",
        "status": "open",
    },
    {
        "id": "itm_002",
        "type": "found",
        "title": "Set of Car Keys",
        "category": "Keys",
        "image": "https://picsum.photos/seed/keys/600/400",
        "location": "Cafeteria Entrance",
        "date": "5 hours ago",
        "status": "open",
    },
    {
        "id": "itm_003",
        "type": "lost",
        "title": "Red ID Wallet",
        "category": "Wallet/ID",
        "image": "https://picsum.photos/seed/wallet/600/400",
        "location": "Dormitory 4",
        "date": "1 day ago",
        "status": "matched",
    },
    {
        "id": "itm_004",
        "type": "found",
        "title": "Blue Backpack",
        "category": "Bag",
        "image": "https://picsum.photos/seed/backpack/600/400",
        "location": "Lecture Hall C",
        "date": "1 hour ago",
        "status": "open",
    },
    {
        "id": "itm_005",
        "type": "lost",
        "title": "Airpods Pro Case",
        "category": "Gadget",
        "image": "https://picsum.photos/seed/airpods/600/400",
        "location": "Gym Locker Room",
        "date": "3 days ago",
        "status": "open",
    },
];
